Tugas3/src/avril/urls.py
from django.urls import path
from avril import views

app_name = 'avril' 
urlpatterns = [
   path('', views.readStudent, name='read-data-student'),   
   path('create/', views.createStudent, name='create-data-student'),   
   path('update/<str:id>', views.updateStudent, name='update-data-student'),  
   path('delete/<str:id>', views.deleteStudent, name='delete-data-student')
]

Tugas3/src/src/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),    path('', include('avril.urls')),]

Tugas3/src/avril/models.py
import uuid
from django.contrib.auth.models import User
from django.db import models
from django.contrib.postgres.functions import RandomUUID
from django.utils import timezone
import uuid


# Create your models here.
class AccountUser(models.Model):
    account_user_id = models.UUIDField(
        primary_key=True, default=uuid.uuid4(), editable=False, unique=True)
    account_user_related_user = models.CharField(max_length=255, null=False, editable=False)
    account_user_fullname = models.CharField(max_length=255, null=False, editable=False)
    account_user_student_number = models.CharField(max_length=20, null=False)
    account_user_created_by = models.CharField(max_length=255, null=False)
    account_user_created_date = models.DateTimeField(editable=False, null=False, auto_now_add=True)
    account_user_updated_by = models.CharField(max_length=255, null=True)
    account_user_updated_date = models.DateTimeField(editable=False, null=False, auto_now_add=True)

    def _str_(self):
        return self.account_user_related_user

    def _unicode_(self):
        return '%s' % self.account_user_related_user

    @property    
    def friendly_profile(self):
        return mark_safe(u"%s <%s>") % (
            escape(self.account_user_id), escape(self.account_user_related_user), 
            escape(self.account_user_fullname), escape(self.account_user_student_number),            
            escape(self.account_user_created_by), escape(self.account_user_created_date),            
            escape(self.account_user_updated_by), escape(self.account_user_updated_date)
        )

    class Meta:
        ordering = ('account_user_related_user',)
        indexes = [models.Index(
            fields=[
                'account_user_id',                
                'account_user_related_user'
                ]), ]

Tugas3/src/avril/forms.py
from django import forms
from avril.models import AccountUser


class StudentRegisterForm(forms.Form):
    fullname = forms.CharField(
        label='Nama Lengkap', label_suffix=" : ", required=True, widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'John Smith'}),        
        help_text="Nama lengkap mahasiswa", error_messages={'required': "Harus Diisi"})
    nim = forms.CharField(
        label='Nim', label_suffix=" : ", required=True, widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': '102988444'}),        
        help_text="nomor induk mahasiswa", error_messages={'required': "Harus Diisi"})
    email = forms.CharField(
        label='email', label_suffix=" : ", required=True, widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'john@smith.co'}),        
        help_text="email aktif", error_messages={'required': "Harus Diisi"})

    class Meta:
        model = AccountUser
        fields = ('account_user_fullname', 'account_user_student_number')

    def clean(self):
        super(StudentRegisterForm, self).clean()

        fullname = self.cleaned_data.get("fullname")
        if not fullname: self._errors['fullname'] = self.error_class(['Harus di isi!'])

        nim = self.cleaned_data.get("nim")
        if not nim: self._errors['nim'] = self.error_class(['Harus di isi!'])

        email = self.cleaned_data.get("email")
        if not email: self._errors['email'] = self.error_class(['Harus di isi!'])

Tugas3/src/avril/views.py
import sys
from django.contrib import messages
from django.db.models.signals import post_save
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from django.db.models import Q
from django.contrib.auth.models import User
from avril.models import AccountUser
from avril.signals import check_nim
from avril.forms import StudentRegisterForm


# Create your views here.
def readStudent(request):
    data = AccountUser.objects.all()

    context = {'data_list': data}

    return render(request, 'index.html', context)


@csrf_protect
def createStudent(request):
    if request.method == 'POST':
        form = StudentRegisterForm(request.POST)
        if form.is_valid():
            post_save.disconnect(check_nim)
            form.fullname = form.cleaned_data.get("fullname")
            form.nim = form.cleaned_data.get("nim")
            form.email = form.cleaned_data.get("email")
            post_save.send(
                sender=AccountUser, created=None,                
                instance=form,                
                dispatch_uid="check_nim")
            messages.success(request, 'Data Berhasil disimpan')
            return redirect('avril:read-data-student')
    else:
        form = StudentRegisterForm()

    return render(request, 'form.html', {'form': form})


@csrf_protect
def updateStudent(request, id):
    #Create Your Task Here...
    member = AccountUser.objects.get(account_user_related_user=id)
    user = User.objects.get(username=id)
    if request.method == 'POST':
        form = StudentRegisterForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            account_user_student_number = form.cleaned_data.get("nim")
            email = form.cleaned_data.get("email")

            if account_user_student_number:
                member.account_user_student_number = account_user_student_number
            else:
                messages.error(request, 'Account user student number is required')
                return render(request, 'form.html', {'form': form})

            user.email = email
            member.save()
            user.save()
            messages.success(request, 'Data Berhasil diupdate')
            return redirect('avril:read-data-student')
        else:
            print(form.errors)
    else:
        initial_data = {
            'fullname': user.first_name + '' + user.last_name,
            'nim': member.account_user_student_number,
            'email': user.email,
        }
        form = StudentRegisterForm(initial=initial_data)
    return render(request, 'form.html', {'form': form})


@csrf_protect
def deleteStudent(request, id):
    member = AccountUser.objects.get(account_user_related_user=id)
    user = User.objects.get(username=id)
    member.delete()
    user.delete()
    messages.success(request, 'Data Berhasil dihapus')
    return redirect('avril:read-data-student')

Tugas3/src/avril/templates/form.html
{% load static %}
{% block content %}
    <div class="container">        
        <div class="row">            
            <div class="main_business">                
                <div class="col-md-12">                    
                    {% if form.errors %}
                    <div class="alert alert-danger">                        
                        <strong>{{form.errors}}</strong>                    
                    </div>                    
                    <br>                    
                    {% endif %}
                </div>            
            </div>        
        </div>    
    </div>    
    <form method="post" id="create-form" name="create-form" >        
        {% csrf_token %}
        <div>            
            <label>Input Nama Lengkap</label>            
            <input type="text" name="fullname" id="fullname">        
        </div>        
        <div>            
            <label>Input NIM Lengkap</label>            
            <input type="text" name="nim" id="nim">        
        </div>        
        <div>            
            <label>Input Email Lengkap</label>            
            <input type="email" name="email" id="email">        
        </div>        <div class="panel-footer text-center">            
            <button class="btn btn-primary m-top-20">                
                Simpan
            </button>        
        </div>    
    </form>{% endblock %}

Tugas3/src/avril/templates/index.html
{% load static %}
{% block content %}
{% if messages %}
    <div class="alert alert-success">        
        {% for message in messages %}
        <strong>{{ message }}</strong>        
        {% endfor %}
    </div>{% endif %}
    <a href="{% url 'avril:create-data-student' %}">Create</a>
    <table border="1">    
        <thead>        
            <tr>            
                <td>NIM</td>            
                <td>Nama</td>            
                <td>e-mail</td>            
                <td>Actions</td>        
            </tr>    
        </thead>    
        <tbody>        
            {% for obj in data_list%}
        <tr>            
            <td>                
                {{obj.account_user_student_number}}
            </td>            
            <td>                
                {{obj.account_user_fullname}}
            </td>            
            <td>{{obj.account_user_related_user}}</td>           
            <td>                
                <a href="{% url 'avril:update-data-student' obj.account_user_related_user %}">Update</a>                
                <br>                
                <a href="{% url 'avril:delete-data-student' obj.account_user_related_user %}">Delete</a>           
            </td>        
        </tr>        {% empty%}
            <h1>Data masih kosong</h1>            
            {% endfor %}
    </tbody></table>{% endblock %}